# OrderPortal: Example settings file.

# Official URL to portal
BASE_URL: 'http://your-domain.com/'

# tornado server port
PORT: 8882

# CouchDB server
DB_SERVER: 'http://localhost:5984/'
# DB_SERVER: 'http://username:password@localhost:5984/'
DATABASE: 'orderportal'

# Logging and debug.
TORNADO_DEBUG: True
LOGGING_DEBUG: True

# Login
COOKIE_SECRET: 'make this a long string with apparent garbage'
PASSWORD_SALT: 'make this a long string with apparent garbage'

# Site customization
SITE_DIR: '{ROOT}/your'
SITE_NAME: 'Your Order Portal'
SITE_FAVICON: 'favicon.png'
SITE_NAVBAR_ICON: 'favicon.png'
SITE_HOME_ICON: 'logo-white-background.png'
SITE_SUPPORT_EMAIL: 'your.email@your-domain.com'

# Use sequentially numbered order identifiers
ORDER_ID_FORMAT: 'YOUR{0:=05d}'
ORDER_ID_REGEXP: 'YOUR\d+'

ORDERS_LIST_STATUSES:
  - submitted
  - accepted
  - processing
  - closed

# Messages; email server info.
MESSAGE_SENDER_EMAIL: '"OrderPortal Support" <support@your-domain.com>'
EMAIL:
  HOST: 'localhost'
